spring:
  cloud:
    gateway:
      routes:
      - id: transaction-module
        uri: http://localhost:8081/
        predicates:
        - Path=/transaction/**
      - id: product-module
        uri: http://localhost:8082/
        predicates:
        - Path=/product/**
      - id: customer-module
        uri: http://localhost:8083/
        predicates:
        - Path=/customer/**